# Generated by Django 4.2.11 on 2024-03-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_driver_user_alter_booking_booking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_license_id',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/license'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_valid_id',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/valid_id'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='toll_fee',
            field=models.IntegerField(default=1000),
        ),
    ]
