# Generated by Django 4.2.11 on 2024-03-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_booking_customer_license_id_booking_customer_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='toll_fee',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
