# Generated by Django 4.2.11 on 2024-03-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_alter_booking_booking_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_total_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
