# Generated by Django 4.2.11 on 2024-03-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_booking_total_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference_number_penalty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
