# Generated by Django 4.2.11 on 2024-03-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_booking_reference_number_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_first_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_first_time',
            field=models.BooleanField(default=True),
        ),
    ]
