# Generated by Django 4.2.11 on 2024-03-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_cars_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
