# Generated by Django 4.2.11 on 2024-04-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_alter_driver_driver_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_seater',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
